services:
  - type: web
    name: fortuna-backend
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 4000
